blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from blog import views

urlpatterns = [
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostEdit.as_view(),
        name = 'post_edit'),
    url(r'^post/new/$', views.PostNew.as_view(), name = 'post_new'),
    url(r'post/(?P<pk>\d+)/delete/$', views.PostDelete.as_view(),
        name = 'post_delete'),
    url(r'post/(?P<pk>\d+)/media/$', views.PostMedia.as_view(),
        name = 'post_media'),
    url(r'^post/(?P<pk>\d+)/$', views.PostDetails.as_view(),
        name = 'post_details'),

    url(r'^page/(?P<page>\d+)/$', views.PostList.as_view(),
        name = 'post_page'),
    url(r'^$', views.PostList.as_view(),
        name = 'post_list'),
]

judge/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from judge import views

urlpatterns = [
    url(r'^$', views.ProblemList.as_view(), 
        name = 'problem_list'),
    url(r'^problems/page/(?P<page>\d+)/$', views.ProblemList.as_view(), 
        name = 'problem_page'),
    url(r'^problems/tags/(?P<tags>[\w ]+(,[\w ]+)*)/$', 
        views.ProblemList.as_view(), name = 'problem_list_tags'),
    url(r'^problems/tags/(?P<tags>[\w ]+(,[\w ]+)*)/page/(?P<page>\d+)/$', 
        views.ProblemList.as_view(), name = 'problem_list_tags_page'),
    url(r'^problems/filter/$', views.ProblemFilter.as_view(),
        name = 'problem_filter'),
    url(r'^problems/(?P<pk>\d+)/$', views.ProblemDetails.as_view(), 
       name = 'problem_details'),

    url(r'^problems/new/', views.ProblemNew.as_view(), 
        name = 'problem_new'),
    url(r'^problems/(?P<pk>\d+)/edit/$', views.ProblemEdit.as_view(), 
        name = 'problem_edit'),
    url(r'^problems/(?P<pk>\d+)/delete/$', views.ProblemDelete.as_view(),
       name = 'problem_delete'),
    url(r'^problems/(?P<pk>\d+)/media/$', views.ProblemMedia.as_view(),
        name = 'problem_media'),
    url(r'^problems/(?P<pk>\d+)/retest/$', views.ProblemRetest.as_view(),
       name = 'problem_retest'),
    url(r'^problems/(?P<pk>\d+)/visibility/$', 
        views.ProblemVisibility.as_view(), name = 'problem_visibility'),
    url(r'^problems/(?P<pk>\d+)/grading/$', views.ProblemGrading.as_view(),
        name = 'problem_grading'),
    url(r'^problems/import/$', views.PorblemImport.as_view(),
        name = 'problem_import'),
    url(r'problems/(?P<pk>\d+)/export/$', views.ProblemExport.as_view(),
        name = 'problem_export'),

    url(r'^problems/(?P<problem_id>\d+)/newtest/$', views.TestNew.as_view(), 
       name = 'test_new'),
    url(r'^problems/(?P<problem_id>\d+)/tests/$', views.TestList.as_view(),
       name = 'test_list'),
    url(r'^test/(?P<pk>\d+)/edit/$', views.TestEdit.as_view(),
       name = 'test_edit'),
    url(r'^test/(?P<ids>\d+(,\d+)*)/delete/$', views.TestDelete.as_view(),
        name = 'test_delete'),
    url(r'^test/(?P<pk>\d+)/input/$', views.TestInput.as_view(),
        name = 'test_input'),
    url(r'^test/(?P<pk>\d+)/output/$', views.TestOutput.as_view(),
        name = 'test_output'),

    url(r'^problems/(?P<problem_id>\d+)/newtestgroup/$',
            views.TestGroupNew.as_view(), name = 'test_group_new'),
    url(r'^testgroup/(?P<pk>\d+)/edit/$',
            views.TestGroupEdit.as_view(), name = 'test_group_edit'),
    url(r'^testgroup/(?P<pk>\d+)/delete/$',
            views.TestGroupDelete.as_view(), name = 'test_group_delete'),

    url(r'^problems/(?P<pk>\d+)/submit/$', views.SolutionSubmit.as_view(), 
        name = 'solution_submit'),
    url(r'^solutions/(?P<pk>\d+)/$', views.SolutionDetails.as_view(),
        name = 'solution_details'),
    url(r'^solutions/(?P<pk>\d+)/source/$', views.SolutionSource.as_view(),
        name = 'solution_source'),
]

judgeSystem/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from djcelery.models import CrontabSchedule, IntervalSchedule, PeriodicTask, \
    TaskState, WorkerState
from taggit.models import Tag

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('judge.urls', namespace = 'judge')),
    url(r'^account/', include('users.urls', namespace = 'users')),
    url(r'^blog/', include('blog.urls', namespace = 'blog')),
    url(r'^media_manager/', include('media_manager.urls', 
        namespace = 'media_manager')),
]
if settings.DEBUG:
    from django.views import static
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', static.serve, {
        'document_root': settings.MEDIA_ROOT})]

admin.site.unregister(CrontabSchedule)
admin.site.unregister(IntervalSchedule)
admin.site.unregister(PeriodicTask)
admin.site.unregister(TaskState)
admin.site.unregister(WorkerState)
admin.site.unregister(Tag)

admin.site.login = login_required(admin.site.login)

judgeSystem/templates/judgeSystem/base.html
{% load bootstrap3 %}
{% load base %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any
	other head content must come *after* these tags -->
	<title>Judge system</title>
	<!-- Bootstrap -->
	<!--<link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.4/cosmo/bootstrap.min.css"
	   rel="stylesheet">-->
	<link
	href='https://fonts.googleapis.com/css?family=Roboto&subset=latin,cyrillic'
	rel='stylesheet' type='text/css'>
	<link
	href='https://fonts.googleapis.com/css?family=Roboto+Mono&subset=latin,cyrillic'
	rel='stylesheet' type='text/css'>

	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

	<link rel="stylesheet"
	   href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/css/select2.min.css"/>
	<link rel="stylesheet" href="{% static 'judgeSystem/core.css' %}">

	{% block stylesheet %} {% endblock %}

	<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	ga('create', 'UA-68406954-1', 'auto');
	ga('send', 'pageview');
	</script>
</head>
<body style="padding-top: 75px;">
	{% block navbar %}
		{% base_nav %}
	{% endblock navbar %}

	<div class="container">
		{% bootstrap_messages %}

		{% block header-div %}
			<div class="page-header">
				{% block title %}
				{% endblock %}
			</div>
		{% endblock %}
		{% block content %}
		{% endblock %}
	</div>

	{% bootstrap_javascript jquery=1 %}
	<script 
		src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/js/select2.min.js"></script>

	<script type="text/javascript" src="{% static 'judgeSystem/core.js' %}"></script>

	{% block javascript %}
	{% endblock %}
</body>
</html>

judgeSystem/templates/judgeSystem/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed"
			data-toggle="collapse" data-target="#navbar-collapse">
				  <span class="sr-only">Toggle navigation</span>
				  <span class="icon-bar"></span>
				  <span class="icon-bar"></span>
				  <span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'judge:problem_list' %}">
				Judge system
			</a>
		</div>
		<div class="collapse navbar-collapse" id="navbar-collapse">
			<ul class="nav navbar-nav">
				{% for page in navLeft %}
					<li class="{% if page.name == curPage %}active{% endif %}">
						<a href="{{ page.url }}">
							{{ page.text }}
						</a>
					</li>
				{% endfor %}
			</ul>
			<ul class="nav navbar-nav navbar-right">
				{% for page in navRight %}
					<li class="{% if page.name == curPage %}active{% endif %}"> 
						<a href="{{ page.url }}">
							{{ page.text }}
						</a> 
					</li>
				{% endfor %}
			</ul>
		</div>
	</div>
</nav>