blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from blog import views

urlpatterns = [
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostEdit.as_view(),
        name = 'post_edit'),
    url(r'^post/new/$', views.PostNew.as_view(), name = 'post_new'),
    url(r'post/(?P<pk>\d+)/delete/$', views.PostDelete.as_view(),
        name = 'post_delete'),
    url(r'post/(?P<pk>\d+)/media/$', views.PostMedia.as_view(),
        name = 'post_media'),
    url(r'^post/(?P<pk>\d+)/$', views.PostDetails.as_view(),
        name = 'post_details'),

    url(r'^page/(?P<page>\d+)/$', views.PostList.as_view(),
        name = 'post_page'),
    url(r'^$', views.PostList.as_view(),
        name = 'post_list'),
]

judgeSystem/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from djcelery.models import CrontabSchedule, IntervalSchedule, PeriodicTask, \
    TaskState, WorkerState
from taggit.models import Tag

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('judge.urls', namespace = 'judge')),
    url(r'^account/', include('users.urls', namespace = 'users')),
    url(r'^blog/', include('blog.urls', namespace = 'blog')),
    url(r'^media_manager/', include('media_manager.urls', 
        namespace = 'media_manager')),
]
if settings.DEBUG:
    from django.views import static
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', static.serve, {
        'document_root': settings.MEDIA_ROOT})]

admin.site.unregister(CrontabSchedule)
admin.site.unregister(IntervalSchedule)
admin.site.unregister(PeriodicTask)
admin.site.unregister(TaskState)
admin.site.unregister(WorkerState)
admin.site.unregister(Tag)

admin.site.login = login_required(admin.site.login)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from markdown_deux import markdown

class BlogPost(models.Model):
    title = models.CharField('Title', max_length = 64, default = 'New Draft')

    HTML = 'html'
    MD = 'md'
    CONTENT_LANGUAGE_CHOICES = (
        (HTML, 'HTML'),
        (MD, 'Markdown'),
    )
    content_language = models.CharField('Language', max_length = 8,
        choices = CONTENT_LANGUAGE_CHOICES, default = HTML)

    content = models.TextField('Content', blank = True, default = '')
    author = models.ForeignKey(User)

    public = models.BooleanField(default = False)
    post_time = models.DateTimeField(default = timezone.now)

    class Meta:
        ordering = ('-post_time',)
        permissions = (
            ('change_foreign_blogpost', 'Edit someone else\'s post'),
            ('add_media_to_blogpost', 'Upload media to a blog post'),
        )

    def get_content_html(self):
        if self.content_language == self.HTML:
            return self.content
        elif self.content_language == self.MD:
            return markdown(self.content)

    def may_edit(self, user):
        if not user.is_authenticated():
            return False
        elif user.has_perm('blog.change_foreign_blogpost'):
            return True
        elif self.author == user:
            return True
        else:
            return False

blog/views.py
import abc

from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin, \
    PermissionRequiredMixin
from django.core.paginator import InvalidPage, Paginator
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.forms import ModelForm
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import View, DetailView, TemplateView

from blog.models import BlogPost

class BlogPostForm(ModelForm):
    class Meta:
        model = BlogPost
        exclude = ['author', 'post_time']

class PostEdit(PermissionRequiredMixin, View):
    permission_required = 'blog.change_blogpost'
    template_name = 'blog/post_edit.html'

    def get_response(self, request, form = BlogPostForm(), post = None):
        context = {
            'form': form,
            'post': post
        }
        return render(request, self.template_name, context)

    def get(self, request, pk):
        post = get_object_or_404(BlogPost, pk = pk)

        if not post.may_edit(request.user):
            raise Http404
        else:
            form = BlogPostForm(instance = post)
            return self.get_response(request, form = form, post = post)

    def post(self, request, pk):
        post = get_object_or_404(BlogPost, pk = pk)
        form = BlogPostForm(request.POST, instance = post)

        if not form.is_valid():
            return self.get_response(request, form = form, post = post)
        else:
            form.save()
            return redirect(reverse('blog:post_details', args = (post.pk,)))

class PostNew(PermissionRequiredMixin, View):
    permission_required = 'blog.add_blogpost'

    def get(self, request):
        post = BlogPost.objects.create(author = request.user)
        return redirect(reverse('blog:post_edit', args = (post.pk,)))

class PostMedia(PermissionRequiredMixin, TemplateView):
    permission_required = 'blog.add_media_to_blogpost'
    template_name = 'blog/post_media.html'

    def get_context_data(self, **kwargs):
        context = super(PostMedia, self).get_context_data(**kwargs)
        context['post'] = get_object_or_404(BlogPost, pk = kwargs['pk'])

        if not context['post'].may_edit(self.request.user):
            raise Http404

        return context

class PostDetails(DetailView):
    model = BlogPost
    context_object_name = 'post'
    template_name = 'blog/post_details.html'

class PostList(TemplateView):
    template_name = 'blog/post_list.html'

    def get_context_data(self, page = 1, **kwargs):
        postsQ = Q(public = True)
        if self.request.user.is_authenticated():
            postsQ |= Q(public = False, author = self.request.user)

        if self.request.user.has_perm('blog.change_foreign_blogpost'):
            postsQ = Q()

        posts = BlogPost.objects.filter(postsQ)
        paginator = Paginator(posts, 5)
        
        try:
            curPage = paginator.page(page)
        except InvalidPage:
            raise Http404

        context = super(PostList, self).get_context_data(**kwargs)
        context['page'] = curPage

        return context

class PostDelete(PermissionRequiredMixin, View):
    permission_required = 'blog.delete_blogpost'
    template_name = 'blog/post_delete.html'

    def get(self, request, pk):
        post = get_object_or_404(BlogPost, pk = pk)
        if not post.may_edit(request.user):
            raise Http404

        context = {
            'post': post
        }
        return render(request, self.template_name, context)

    def post(self, request, pk):
        post = get_object_or_404(BlogPost, pk = pk)
        post.delete()

        messages.success(request, 'Blog post deleted successfully')
        return redirect(reverse('blog:post_list'))

blog/templates/blog/base.html
{% extends base_template %}
{% load base %}

{% block navbar %}
	{% base_nav page='blog' %}
{% endblock %}

blog/templates/blog/post_admin_panel.html
{% if has_permission %}
	{% if post %}
		<a href="{% url 'blog:post_edit' post.pk %}"
			style="float:right;" class="btn btn-info btn-sm">
			Edit
		</a>
	{% else %}
		<a href="{% url 'blog:post_new' %}"
			style="float:right;" class="btn btn-info btn-sm">
			New blog post
		</a>
	{% endif %}
{% endif %}

blog/templates/blog/post_delete.html
{% extends 'blog/post_edit_base.html' %}
{% load blog %}

{% block title %}
	<h1> Delete blog post </h1>
{% endblock %}

{% block breadcrumb_active %}
    Delete
{% endblock %}

{% block edit_content %}
	<p class="lead">
		Are you sure you want to delete this blog post ?
		It will be deleted <span class="text-danger">FOREVER</span>
	</p>
	<form method="POST" action="{{ request.get_full_path }}">
		{% csrf_token %}
		<input type="submit" value="Delete blog post"
			class="btn btn-danger btn-block">
	</form>
{% endblock %}

{% block edit_nav %}
	{% blog_post_edit_nav post=post page='delete' %}
{% endblock %}

blog/templates/blog/post_details.html
{% extends 'blog/base.html' %}
{% load blog %}

{% block title %}
    <ol class="breadcrumb">
        <li><a href="{% url 'blog:post_list' %}">Blog</a></li>
        <li class="active">{{ post.title }}</li>
    </ol>
	<h1> 
		{{ post.title }}
		{% if not post.public %}
			<small>Draft</small>
		{% endif %}
		{% post_admin_panel post=post %}
	</h1>
	<p class="lead">
		{{ post|post_subheading }}
	</p>
{% endblock %}

{% block content %}
	{{ post.get_content_html|safe }}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/post_edit_base.html' %}
{% load bootstrap3 %}
{% load blog %}

{% block title %}
	<h1>Edit blog post</h1>
{% endblock %}

{% block edit_nav %}
	{% blog_post_edit_nav post=post page='edit' %}
{% endblock %}

{% block breadcrumb_active %}
    Edit
{% endblock %}

{% block edit_content %}
	<form method="POST" action="{{ request.get_full_path }}">
		{% bootstrap_form form %}
		{% csrf_token %}

		<input type="submit" value="Save" class="btn btn-primary btn-block">
	</form>
{% endblock %}

blog/templates/blog/post_edit_base.html
{% extends 'blog/base.html' %}
{% load blog %}

{% block content %}
    <ol class="breadcrumb">
        <li>
            <a href="{% url 'blog:post_list' %}">
                Blog
            </a>
        </li>
        <li>
            <a href="{% url 'blog:post_details' post.pk %}">
                {{ post.title }}
            </a>
        </li>
        <li class="active">
            {% block breadcrumb_active %}{% endblock %}
        </li>
    </ol>
	<div class="row">
		<div class="col-md-3">
			{% block edit_nav %}{% endblock %}
		</div>
		<div class="col-md-9">
			{% block edit_content %}{% endblock %}
		</div>
	</div>
{% endblock content %}

blog/templates/blog/post_edit_nav.html
<ul class="nav nav-pills nav-stacked">
	{% for page in pages %}
		<li {% if page.name == curPage %} class="active" {%endif%}>
			<a href="{{ page.url }}">
				{{ page.text }}
			</a>
		</li>
	{% endfor %}
</ul>

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% load blog %}
{% load bootstrap_pagination %}

{% block title %}
	<h1>
		Blog
		{% post_admin_panel %}
	</h1>
{% endblock %}

{% block content %}
    <ol class="breadcrumb">
        <li class="active">Blog</li>
    </ol>
	{% for post in page.object_list %}
		<h2> 
			{{ post.title }} 
			{% if not post.public %}
				<small>Draft</small>
			{% endif %}
			{% post_admin_panel post=post %}
		</h2>
		<p class="lead">
			{{ post|post_subheading }}
		</p>
		{{ post.get_content_html|safe|truncatewords_html:100 }}
		<a href="{% url 'blog:post_details' post.pk %}">
			Read the full blog post
		</a>
		<hr>
	{% empty %}
		<p class="lead">
			No blog posts were found
		</p>
	{% endfor %}
	<br>
	{% bootstrap_paginate page url_view_name='blog:post_page' range=20%}
{% endblock %}

blog/templates/blog/post_media.html
{% extends 'blog/post_edit_base.html' %}
{% load blog %}
{% load media_manager %}

{% block title %}
	<h1>Manage media</h1>
{% endblock %}

{% block breadcrumb_active %}
    Manage media
{% endblock %}

{% block edit_content %}
	<h3>Upload Media</h3>
	{% media_upload post %}
	<h3>Media for this blog post</h3>
	{% media_list post %}
{% endblock %}

{% block edit_nav %}
	{% blog_post_edit_nav post=post page='media' %}
{% endblock %}