blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from blog import views

urlpatterns = [
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostEdit.as_view(),
        name = 'post_edit'),
    url(r'^post/new/$', views.PostNew.as_view(), name = 'post_new'),
    url(r'post/(?P<pk>\d+)/delete/$', views.PostDelete.as_view(),
        name = 'post_delete'),
    url(r'post/(?P<pk>\d+)/media/$', views.PostMedia.as_view(),
        name = 'post_media'),
    url(r'^post/(?P<pk>\d+)/$', views.PostDetails.as_view(),
        name = 'post_details'),

    url(r'^page/(?P<page>\d+)/$', views.PostList.as_view(),
        name = 'post_page'),
    url(r'^$', views.PostList.as_view(),
        name = 'post_list'),
]

judgeSystem/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from djcelery.models import CrontabSchedule, IntervalSchedule, PeriodicTask, \
    TaskState, WorkerState
from taggit.models import Tag

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('judge.urls', namespace = 'judge')),
    url(r'^account/', include('users.urls', namespace = 'users')),
    url(r'^blog/', include('blog.urls', namespace = 'blog')),
    url(r'^media_manager/', include('media_manager.urls', 
        namespace = 'media_manager')),
]
if settings.DEBUG:
    from django.views import static
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', static.serve, {
        'document_root': settings.MEDIA_ROOT})]

admin.site.unregister(CrontabSchedule)
admin.site.unregister(IntervalSchedule)
admin.site.unregister(PeriodicTask)
admin.site.unregister(TaskState)
admin.site.unregister(WorkerState)
admin.site.unregister(Tag)

admin.site.login = login_required(admin.site.login)

users/urls.py
from django.conf.urls import url

from users import views

urlpatterns = [
    url(r'^login/$', views.Login.as_view(), name = 'login'),
    url(r'^register/$', views.Register.as_view(), name = 'register'),
    url(r'^activate/(?P<code>\w+)/$', views.Confirm.as_view(), name = 
        'activate'),
    url(r'^logout/$', views.Logout.as_view(), name = 'logout'),

    url(r'^passwordreset/$', views.ResetPassword.as_view(), name = 
        'password_reset'),
    url(r'^setpassword/(?P<code>\w+)/$', views.SetPassword.as_view(), name = 
        'password_set'),

    url(r'^changepassword/$', views.PasswordChange.as_view(), name = 
        'change_password'),
    url(r'^$', views.UserDetails.as_view(), name = 'details'),
    url(r'^manage/$', views.UserManage.as_view(), name = 'manage'),

    url(r'^solutions/$', views.Solutions.as_view(), name = 'solutions'),
    url(r'^solutions/page/(?P<page>\d+)/$', views.Solutions.as_view(), name = 
        'solutions_page'),
]

users/models.py
import string, random

from django.contrib.auth.models import User
from django.db import models
from django.dispatch import receiver
from django.utils import timezone

def gen_randcode():
    chars = string.ascii_uppercase + string.digits
    return ''.join(random.SystemRandom().choice(chars) for i in range(32))

class UserLink(models.Model):
    code = models.CharField(max_length = 32, default = gen_randcode)
    user = models.OneToOneField(User)
    created = models.DateTimeField(default = timezone.now)

    def gen_new_code(self):
        self.code = gen_randcode()
        self.save()

    class Meta:
        abstract = True

class Confirmation(UserLink):
    def __str__(self):
        return self.user.username + ' confirmation ' + self.code

class PassReset(UserLink):
    def __str__(self):
        return self.user.username + ' password reset ' + self.code

users/forms.py
from django.contrib.auth.models import User
from django.forms import Form, CharField, PasswordInput, EmailField

from captcha.fields import ReCaptchaField

password1_kwargs = {
    'label': 'Password',
    'min_length': 6, 
    'max_length': 20,
    'widget': PasswordInput(), 
    'error_messages': { 
        'required': 'Password is required',
        'min_length': 'Password should be at least 6 characters long',
        'max_length': 'Password should be at most 30 characters long'
    }
}

password2_kwargs = {
    'label': 'Confirm password', 
    'widget': PasswordInput(),
    'error_messages': {'required': 'Confirm password'}
}

username_kwargs = {
    'label': 'User Name', 
    'min_length': 6, 
    'max_length': 30, 
    'error_messages': {
        'required': 'Username is required',
        'unique': 'Username is already used',
        'min_length': 'Username should be at least 6 characters long',
        'max_length': 'Username should be less than 30 chracters long'
    }
}

email_kwargs = {
    'label': 'E-mail', 
    'error_messages': {'required': 'E-mail is required'}
}

class LoginForm(Form):
    username = CharField(label = 'User Name',
            error_messages = {'required': 'Username is required'})
    password = CharField(label = 'Password', widget = PasswordInput(),
            error_messages = {'required': 'Password is required'})

class PasswordForm(Form):
    password1 = CharField(**password1_kwargs)
    password2 = CharField(**password2_kwargs)

    def is_valid(self):
        valid = super(PasswordForm, self).is_valid()
        
        data = self.cleaned_data
        if not data.get('password1') == data.get('password2'):
            self.add_error('password2', 'Passwords don\'t match')
            valid = False

        return valid

class RegisterForm(Form):
    username = CharField(**username_kwargs)
    email = EmailField(**email_kwargs)
    password1 = CharField(**password1_kwargs)
    password2 = CharField(**password2_kwargs)

    captcha = ReCaptchaField()

    def is_valid(self):
        valid = super(RegisterForm, self).is_valid()
        
        data = self.cleaned_data
        if not data.get('password1') == data.get('password2'):
            self.add_error('password2', 'Passwords don\'t match')
            valid = False

        if User.objects.filter(username = data.get('username')).exists():
            self.add_error('username', 'Username already taken')
            valid = False

        if User.objects.filter(email = data.get('email')).exists():
            self.add_error('email', 'Email already used')
            valid = False

        return valid

class ResetForm(Form):
    email = EmailField(**email_kwargs)
    captcha = ReCaptchaField()

    def is_valid(self):
        valid = super(ResetForm, self).is_valid()

        email = self.cleaned_data.get('email')
        if not User.objects.filter(email = email).exists():
            self.add_error('email', 'No such email')
            valid = False
            
        return valid

judge/views/login.py
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.mail import EmailMultiAlternatives
from django.core.urlresolvers import reverse
from django.forms import Form, CharField, PasswordInput, EmailField
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template import Context
from django.template.loader import get_template
from django.views.generic import View 

from judge.models import Confirmation

class LoginForm(Form):
    username = CharField(label = 'User Name',
            error_messages = {'required': 'Username is required'})
    password = CharField(label = 'Password', widget = PasswordInput(),
            error_messages = {'required': 'Password is required'})

class Login(View):
    def render_form(self, request, form):
        template_name = 'judge/login.html'
        context = {'form': form}

        return render(request, template_name, context)

    def get(self, request):
        return self.render_form(request, LoginForm())

    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)

        if not form.is_valid():
            return self.render_form(request, form)

        user = authenticate(
            username = form.cleaned_data['username'], 
            password = form.cleaned_data['password'])

        if user is None:
            form.add_error('password', 
                           'Wrong username or password')

            return self.render_form(request, form)
        
        elif not user.is_active:
            form.add_error('username', 'User is not active')
            return self.render_form(request, form)

        else:
            login(request, user)
            redir_url = request.GET.get('next', reverse('judge:problem_list'))
            return HttpResponseRedirect(redir_url)

class RegisterForm(Form):
    username = CharField(label = 'User Name', min_length = 6, 
            max_length = 30, error_messages = {
            'required': 'Username is required',
            'unique': 'Username is already used',
            'min_length': 'Username should be at least \
                    6 characters long',
            'max_length': 'Username should be less \
                    than 30 chracters long'})

    email = EmailField(label = 'E-mail', error_messages = {
                'required': 'E-mail is required'})

    password1 = CharField(label = 'Password',  min_length = 6, 
            max_length = 20, widget = PasswordInput(), 
            error_messages = { 
                'required': 'Password is required',
                'min_length': 'Password should be at least \
                               6 characters long',
                'max_length': 'Password should be at most\
                               30 characters long'})

    password2 = CharField(label = 'Confirm password', 
            widget = PasswordInput(), error_messages = 
            { 'required': 'Confirm password'})

    def is_valid(self):
        valid = super(RegisterForm, self).is_valid()
        
        data = self.cleaned_data
        if not data.get('password1') == data.get('password2'):
            self.add_error('password2', 'Passwords don\'t match')
            valid = False

        if User.objects.filter(username = data.get('username')).exists():
            self.add_error('username', 'Username already taken')
            valid = False

        if User.objects.filter(email = data.get('email')).exists():
            self.add_error('email', 'Email already used')
            valid = False

        return valid

class Register(View):
    template_name = 'judge/register.html'

    def render(self, request):
        context = { 'form': self.form}
        return render(request, self.template_name, context)

    def get(self, request):
        self.form = RegisterForm()
        return self.render(request)
    
    def get_user(self):
        email = self.form.cleaned_data.get('email')
        username = self.form.cleaned_data.get('username')
        password = self.form.cleaned_data.get('password1')

        user = User.objects.create_user(username, email, password)
        user.is_active = False
        user.save()
        return user

    def send_conf_mail(self):
        conf_loc_url = reverse('judge:activate', args=(self.confirm.code,))
        conf_url = settings.SITE_HOST + conf_loc_url

        sender = settings.EMAIL_HOST_USER
        to = self.user.email
        subject = 'JudgeSystem account confirmation'

        plaintext = get_template('judge/confirm_email.txt')
        html      = get_template('judge/confirm_email.html')
        
        context = Context({
            'username': self.user.username, 'conf_url': conf_url})

        text_content = plaintext.render(context)
        html_content = html.render(context)

        msg = EmailMultiAlternatives(subject, text_content, sender, [to])
        msg.attach_alternative(html_content, 'text/html')
        msg.send()

    def post(self, request):
        self.form = RegisterForm(request.POST)
        
        if not self.form.is_valid():
            return self.render(request)

        self.user = self.get_user()
        self.confirm = Confirmation(user = self.user)
        self.confirm.save()

        self.send_conf_mail()

        redir_url = reverse('judge:problem_list')
        return HttpResponseRedirect(redir_url)

class Logout(View):
    def get(self, request):
        logout(request)
        url = reverse('judge:problem_list')
        return HttpResponseRedirect(url)

class Confirm(View):
    def get(self, request, code):
        confList = Confirmation.objects.filter(code = code)

        if not confList.exists():
            error_url = reverse('judge:problem_list')
            return HttpResponseRedirect(error_url)

        conf = confList[0]
        conf.delete()

        user = conf.user
        user.is_active = True
        user.save()

        redir_url = reverse('judge:login')
        return HttpResponseRedirect(redir_url)

judge/views/solution.py
import datetime

from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.urlresolvers import reverse
from django.forms import Form, CharField, Textarea
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseRedirect,\
        HttpResponseForbidden
from django.views.generic import DetailView, View
from django.utils import timezone

from judge.models import Solution, Problem, UserProblemData, UserStats
from judge.tasks import test_solution

class MayViewSolutionMixin(UserPassesTestMixin):
    def test_func(self):
        if self.request.user.has_perm('judge.view_foreign_solution'):
            return True
        else:
            pk = self.request.path_info.split('/')[2]
            solution = get_object_or_404(Solution, pk = int(pk))
            return solution.user_id == self.request.user.id

class SolutionDetails(MayViewSolutionMixin,View):
    template_name = 'judge/solution_details.html'

    def get(self, request, pk):
        sol = get_object_or_404(Solution, pk = pk)
        
        context = { 
            'solution': sol,
            'results_by_group': sol.get_results_by_group(),
            'pk': sol.pk,
        }
        return render(request, self.template_name, context)

class SolutionSource(MayViewSolutionMixin, View):
    def get(self, request, pk):
        sol = get_object_or_404(Solution, pk = pk)
        return HttpResponse(sol.source, content_type = 'text/plain')

class SolutionSubmitForm(Form):
    source = CharField(label = 'Source Code',
                            widget = Textarea())

class SolutionSubmit(LoginRequiredMixin, View):
    template_name = 'judge/solution_submit.html'
            
    def render(self, request):
        context = {
            'problem': self.problem,
            'form': self.form,}
        return render(request, self.template_name, context)

    def get(self, request, pk):
        self.form = SolutionSubmitForm()
        if request.user.has_perm('judge.problem_hidden'):
            self.problem = get_object_or_404(Problem, pk = pk)
        else:
            self.problem = get_object_or_404(Problem, pk = pk, visible = True)

        return self.render(request)

    def post(self, request, pk):
        self.problem = get_object_or_404(Problem, pk = pk)
        self.form = SolutionSubmitForm(request.POST)
        
        user = request.user

        if not self.form.is_valid():
            return self.render(request)

        data = UserProblemData.get_for_user_problem(user, self.problem)
        nextSubmit = data.last_submit + datetime.timedelta(seconds = 30)

        if nextSubmit > timezone.now():
            timeLeft = nextSubmit - timezone.now()
            messageText = 'You can submit a solution once every 30 seconds.\
                Try again in {0} seconds'. format(timeLeft.seconds)
            messages.warning(request, messageText)
            return self.render(request)
        else:
            data.last_submit = timezone.now()
            data.save()

        source = self.form.cleaned_data['source']
        solution = Solution(
            source = source,
            submit_date = timezone.now(),
            user = user,
            problem = self.problem)

        solution.save()
        test_solution(solution).delay()

        url = reverse('judge:solution_details', args = (solution.pk,))
        return HttpResponseRedirect(url)

users/templates/users/base_narrow.html
{% extends base_template %}
{% load static %}

{% block header-div %}
	<div class="page-header narrow">
		{% block title %}
		{% endblock %}
	</div>
{% endblock %}

{% block content %}
	<div class="narrow">
		{% block content_narrow %}
		{% endblock %}
	</div>
{% endblock %}

users/templates/users/change_password.html
{% extends details_base %}
{% load bootstrap3 %}
{% load users %}

{% block title %}
	<h1>Change password</h1>
{% endblock %}

{% block user_nav %}
	{% user_nav page='change_password' %}
{% endblock %}

{% block user_content %}
		<h3>Password change</h3>
		<form method="POST" action="{{ request.get_full_path }}">
			{% bootstrap_form passwordForm %}
			{% csrf_token %}

			{% buttons%}
				<input type="submit" class="btn btn-primary btn-block" 
				   value="Change password">
			{% endbuttons %}
		</form>
{% endblock %}

users/templates/users/login.html
{% extends 'users/base_narrow.html' %}

{% load base %}
{% load bootstrap3 %}

{% block navbar %}
	{% base_nav page='login' %}
{% endblock %}

{% block title %}
	<h1> Login </h1>
{% endblock %}

{% block content_narrow %}
	<form method = "POST" action = "{{request.get_full_path}}">
		{% csrf_token %}
		{% bootstrap_form form %}

		<div class="row">
			<div class="col-md-6">
				{% buttons %}
					<input type="submit" value="Log in"
						  class="btn btn-primary btn-block">
				{% endbuttons %}
			</div>
			<div class="col-md-6">
				{% buttons %}
					<a href="{% url 'users:register' %}" 
						class="btn btn-block btn-default">
							Register
					</a>
				{% endbuttons %}
			</div>
		</div>
	</form>
	<a href="{% url 'users:password_reset' %}" >
		Reset password
	</a>

{% endblock %}

users/templates/users/password_reset.html
{% extends 'users/base_narrow.html' %}
{% load bootstrap3 %}

{% block title %}
	<h1>Password reset</h1>
{% endblock %}

{% block content_narrow %}
<form method="POST" action="{{request.get_full_path}}">
	{% bootstrap_form form %}
	{% csrf_token %}

	<div class="row">
		<div class="col-md-6">
			{% buttons %}
			<input type="submit" value="Reset password"
				 class="btn btn-primary btn-block">
			{% endbuttons %}
		</div>
		<div class="col-md-6">
			{% buttons %}
			<a href="{% url 'users:login' %}"
				class="btn btn-default btn-block">
				Login
			</a>
			{% endbuttons %}
		</div>
	</div>
</form>
{% endblock content_narrow %}

users/templates/users/password_set.html
{% extends 'users/base_narrow.html' %}
{% load bootstrap3 %}

{% block title %}
	<h1>Set a password</h1>
{% endblock %}

{% block content_narrow %}
	<form method="POST" action="{{request.get_full_path}}">
		{% bootstrap_form form %}	
		{% csrf_token %}

		{% buttons %}
			<input type="submit" value="Reset password"
				class="btn btn-primary btn-block">
		{% endbuttons %}
	</form>
{% endblock %}

users/templates/users/register.html
{% extends 'users/base_narrow.html' %}

{% load base %}
{% load bootstrap3 %}

{% block navbar %}
	{% base_nav page='register' %}
{% endblock %}

{% block title %}
	<h1>Register</h1> 
{% endblock %}

{% block content_narrow %}
	<form method="POST" action="{{ request.get_full_path}}">
		{% csrf_token %}
		{% bootstrap_form form %}

		<div class="row">
			<div class="col-md-6">
				{% buttons %}
					<input type="submit" value="Register"
						  class="btn btn-primary btn-block">
				{% endbuttons %}
			</div> 
			<div class="col-md-6">
				{% buttons %}
					<a href="{% url 'users:login' %}" 
						class="btn btn-default btn-block">
						Log in
					</a>
				{% endbuttons %}
			</div>
		</div>
	</form>
{% endblock %}

users/templates/users/solutions.html
{% extends details_base %}

{% load bootstrap_pagination %}
{% load users %}
{% load judge %}

{% block title %}
	<h1>Your solutions</h1>
{% endblock %}

{% block user_content %}
	{% list_solutions page.object_list show_problem=True %}
	{% bootstrap_paginate page url_view_name='users:solutions_page' range=5 %}
{% endblock %}

{% block user_nav %}
	{% user_nav page='solutions' %}
{% endblock %}

users/templates/users/user_details.html
{% extends details_base  %}
{% load bootstrap3 %}
{% load users %}

{% block title %}
	<h1>Account details</h1>
{% endblock %}

{% block user_nav %}
	{% user_nav page='details' %}
{% endblock %}

{% block user_content %}
	<table class="table">
		<tbody>
			{% for row in details %}
				<tr>
					<th>{{ row.0 }}</th>
					<td>{{ row.1 }}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

users/templates/users/user_details_base.html
{% extends base_template  %}
{% load users %}
{% load base %}

{% block navbar %}
	{% base_nav page='user_details' %}
{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-3">
			{% block user_nav %}
				{% user_nav %}
			{% endblock %}
		</div>
		<div class="col-md-9">
			{% block user_content %}{% endblock %}
		</div>
	</div>
{% endblock %}

users/templates/users/user_details_nav.html
<ul class="nav nav-pills nav-stacked">
	<li {% if page == 'details' %} class="active" {% endif %}>
		<a href="{% url 'users:user_details' %}">
			Details
		</a>	
	</li>
	<li {% if page == 'password_change' %} class="active" {% endif %}>
		<a href="{% url 'users:password_change' %}">
			Change password
		</a>
	</li>
	<li {% if page == 'last_subimssions' %} class="active" {% endif %}>
		<a href="">
			Last submissions
		</a>
	</li>
</ul>

users/templates/users/user_manage.html
{% extends details_base %}
{% load bootstrap3 %}
{% load users %}

{% block title %}
	<h1>Manage users</h1>
{% endblock %}

{% block user_nav %}
	{% user_nav page='manage' %}
{% endblock %}

{% block user_content %}
	{% csrf_token %}
	{% for group in groups %}
	<div class="panel panel-default">
		<div class="panel-heading">
			{{ group.name }}
		</div>

		<div class="panel-body">
		<div class="row">	
			<div class="col-md-4">
				<h4> Add users </h4>
				<form method="POST" action="{{ request.get_full_path }}">
					{{ group.form }}
					<div class="form-group">
						<select class="user-select form-control" name="user_id">
							{% for user in allUsers %}
								{% if not user in group.users %}
									<option value="{{ user.id }}">
										{{ user.username }}
									</option>
								{% endif %}
							{% endfor %}
						</select>
					</div>
					{% csrf_token %}
					<div class="form-group">
						<input type="submit" value="Add"
						   class="btn btn-primary form-control">
					</div>
				</form>
			</div>
			<div class="col-md-8">
				<h4>Current users</h4>
				<ul class="list-group">

				{% for entry in group.entries %}
				<li class="list-group-item">
					<form method="POST" action="{{ request.get_full_path }}">
						{{ entry.name }}
						{{ entry.form }}
						{% csrf_token %}

						<a class="btn-right a-submit" href="#">
							<span class="glyphicon glyphicon-remove text-danger">
							</span>
						</a>

					</form>
				</li>
				{% endfor %}
				</ul>
			</div>
		</div>
		</div>
	</div>
	{% endfor %}

{% endblock %}
{% block javascript %}
{{ block.super }}
<script>
	$(document).ready(function() {
		$('.user-select').select2({
			placeholder: 'Add a user'
		});
		$('.a-submit').click(function() {
			$(this).parent().submit();
		});
	});
</script>
{% endblock %}

users/templates/users/user_password_change.html
{% extends base_template %}
{% load bootstrap3 %}

{% block title %}
	<h1>Change password</h1>
{% endblock %}

{% block content %}
		<form method="POST" action="{{ request.get_full_path }}">
			{% bootstrap_form passwordForm %}
			{% csrf_token %}

			<input type="submit" class="btn btn-primary" 
			   value="Change password">
		</form>
{% endblock %}