blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from blog import views

urlpatterns = [
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostEdit.as_view(),
        name = 'post_edit'),
    url(r'^post/new/$', views.PostNew.as_view(), name = 'post_new'),
    url(r'post/(?P<pk>\d+)/delete/$', views.PostDelete.as_view(),
        name = 'post_delete'),
    url(r'post/(?P<pk>\d+)/media/$', views.PostMedia.as_view(),
        name = 'post_media'),
    url(r'^post/(?P<pk>\d+)/$', views.PostDetails.as_view(),
        name = 'post_details'),

    url(r'^page/(?P<page>\d+)/$', views.PostList.as_view(),
        name = 'post_page'),
    url(r'^$', views.PostList.as_view(),
        name = 'post_list'),
]

judge/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from judge import views

urlpatterns = [
    url(r'^$', views.ProblemList.as_view(), 
        name = 'problem_list'),
    url(r'^problems/page/(?P<page>\d+)/$', views.ProblemList.as_view(), 
        name = 'problem_page'),
    url(r'^problems/tags/(?P<tags>[\w ]+(,[\w ]+)*)/$', 
        views.ProblemList.as_view(), name = 'problem_list_tags'),
    url(r'^problems/tags/(?P<tags>[\w ]+(,[\w ]+)*)/page/(?P<page>\d+)/$', 
        views.ProblemList.as_view(), name = 'problem_list_tags_page'),
    url(r'^problems/filter/$', views.ProblemFilter.as_view(),
        name = 'problem_filter'),
    url(r'^problems/(?P<pk>\d+)/$', views.ProblemDetails.as_view(), 
       name = 'problem_details'),

    url(r'^problems/new/', views.ProblemNew.as_view(), 
        name = 'problem_new'),
    url(r'^problems/(?P<pk>\d+)/edit/$', views.ProblemEdit.as_view(), 
        name = 'problem_edit'),
    url(r'^problems/(?P<pk>\d+)/delete/$', views.ProblemDelete.as_view(),
       name = 'problem_delete'),
    url(r'^problems/(?P<pk>\d+)/media/$', views.ProblemMedia.as_view(),
        name = 'problem_media'),
    url(r'^problems/(?P<pk>\d+)/retest/$', views.ProblemRetest.as_view(),
       name = 'problem_retest'),
    url(r'^problems/(?P<pk>\d+)/visibility/$', 
        views.ProblemVisibility.as_view(), name = 'problem_visibility'),
    url(r'^problems/(?P<pk>\d+)/grading/$', views.ProblemGrading.as_view(),
        name = 'problem_grading'),
    url(r'^problems/import/$', views.PorblemImport.as_view(),
        name = 'problem_import'),
    url(r'problems/(?P<pk>\d+)/export/$', views.ProblemExport.as_view(),
        name = 'problem_export'),

    url(r'^problems/(?P<problem_id>\d+)/newtest/$', views.TestNew.as_view(), 
       name = 'test_new'),
    url(r'^problems/(?P<problem_id>\d+)/tests/$', views.TestList.as_view(),
       name = 'test_list'),
    url(r'^test/(?P<pk>\d+)/edit/$', views.TestEdit.as_view(),
       name = 'test_edit'),
    url(r'^test/(?P<ids>\d+(,\d+)*)/delete/$', views.TestDelete.as_view(),
        name = 'test_delete'),
    url(r'^test/(?P<pk>\d+)/input/$', views.TestInput.as_view(),
        name = 'test_input'),
    url(r'^test/(?P<pk>\d+)/output/$', views.TestOutput.as_view(),
        name = 'test_output'),

    url(r'^problems/(?P<problem_id>\d+)/newtestgroup/$',
            views.TestGroupNew.as_view(), name = 'test_group_new'),
    url(r'^testgroup/(?P<pk>\d+)/edit/$',
            views.TestGroupEdit.as_view(), name = 'test_group_edit'),
    url(r'^testgroup/(?P<pk>\d+)/delete/$',
            views.TestGroupDelete.as_view(), name = 'test_group_delete'),

    url(r'^problems/(?P<pk>\d+)/submit/$', views.SolutionSubmit.as_view(), 
        name = 'solution_submit'),
    url(r'^solutions/(?P<pk>\d+)/$', views.SolutionDetails.as_view(),
        name = 'solution_details'),
    url(r'^solutions/(?P<pk>\d+)/source/$', views.SolutionSource.as_view(),
        name = 'solution_source'),
]

judgeSystem/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from djcelery.models import CrontabSchedule, IntervalSchedule, PeriodicTask, \
    TaskState, WorkerState
from taggit.models import Tag

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('judge.urls', namespace = 'judge')),
    url(r'^account/', include('users.urls', namespace = 'users')),
    url(r'^blog/', include('blog.urls', namespace = 'blog')),
    url(r'^media_manager/', include('media_manager.urls', 
        namespace = 'media_manager')),
]
if settings.DEBUG:
    from django.views import static
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', static.serve, {
        'document_root': settings.MEDIA_ROOT})]

admin.site.unregister(CrontabSchedule)
admin.site.unregister(IntervalSchedule)
admin.site.unregister(PeriodicTask)
admin.site.unregister(TaskState)
admin.site.unregister(WorkerState)
admin.site.unregister(Tag)

admin.site.login = login_required(admin.site.login)

users/urls.py
from django.conf.urls import url

from users import views

urlpatterns = [
    url(r'^login/$', views.Login.as_view(), name = 'login'),
    url(r'^register/$', views.Register.as_view(), name = 'register'),
    url(r'^activate/(?P<code>\w+)/$', views.Confirm.as_view(), name = 
        'activate'),
    url(r'^logout/$', views.Logout.as_view(), name = 'logout'),

    url(r'^passwordreset/$', views.ResetPassword.as_view(), name = 
        'password_reset'),
    url(r'^setpassword/(?P<code>\w+)/$', views.SetPassword.as_view(), name = 
        'password_set'),

    url(r'^changepassword/$', views.PasswordChange.as_view(), name = 
        'change_password'),
    url(r'^$', views.UserDetails.as_view(), name = 'details'),
    url(r'^manage/$', views.UserManage.as_view(), name = 'manage'),

    url(r'^solutions/$', views.Solutions.as_view(), name = 'solutions'),
    url(r'^solutions/page/(?P<page>\d+)/$', views.Solutions.as_view(), name = 
        'solutions_page'),
]

judge/views/login.py
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.mail import EmailMultiAlternatives
from django.core.urlresolvers import reverse
from django.forms import Form, CharField, PasswordInput, EmailField
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template import Context
from django.template.loader import get_template
from django.views.generic import View 

from judge.models import Confirmation

class LoginForm(Form):
    username = CharField(label = 'User Name',
            error_messages = {'required': 'Username is required'})
    password = CharField(label = 'Password', widget = PasswordInput(),
            error_messages = {'required': 'Password is required'})

class Login(View):
    def render_form(self, request, form):
        template_name = 'judge/login.html'
        context = {'form': form}

        return render(request, template_name, context)

    def get(self, request):
        return self.render_form(request, LoginForm())

    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)

        if not form.is_valid():
            return self.render_form(request, form)

        user = authenticate(
            username = form.cleaned_data['username'], 
            password = form.cleaned_data['password'])

        if user is None:
            form.add_error('password', 
                           'Wrong username or password')

            return self.render_form(request, form)
        
        elif not user.is_active:
            form.add_error('username', 'User is not active')
            return self.render_form(request, form)

        else:
            login(request, user)
            redir_url = request.GET.get('next', reverse('judge:problem_list'))
            return HttpResponseRedirect(redir_url)

class RegisterForm(Form):
    username = CharField(label = 'User Name', min_length = 6, 
            max_length = 30, error_messages = {
            'required': 'Username is required',
            'unique': 'Username is already used',
            'min_length': 'Username should be at least \
                    6 characters long',
            'max_length': 'Username should be less \
                    than 30 chracters long'})

    email = EmailField(label = 'E-mail', error_messages = {
                'required': 'E-mail is required'})

    password1 = CharField(label = 'Password',  min_length = 6, 
            max_length = 20, widget = PasswordInput(), 
            error_messages = { 
                'required': 'Password is required',
                'min_length': 'Password should be at least \
                               6 characters long',
                'max_length': 'Password should be at most\
                               30 characters long'})

    password2 = CharField(label = 'Confirm password', 
            widget = PasswordInput(), error_messages = 
            { 'required': 'Confirm password'})

    def is_valid(self):
        valid = super(RegisterForm, self).is_valid()
        
        data = self.cleaned_data
        if not data.get('password1') == data.get('password2'):
            self.add_error('password2', 'Passwords don\'t match')
            valid = False

        if User.objects.filter(username = data.get('username')).exists():
            self.add_error('username', 'Username already taken')
            valid = False

        if User.objects.filter(email = data.get('email')).exists():
            self.add_error('email', 'Email already used')
            valid = False

        return valid

class Register(View):
    template_name = 'judge/register.html'

    def render(self, request):
        context = { 'form': self.form}
        return render(request, self.template_name, context)

    def get(self, request):
        self.form = RegisterForm()
        return self.render(request)
    
    def get_user(self):
        email = self.form.cleaned_data.get('email')
        username = self.form.cleaned_data.get('username')
        password = self.form.cleaned_data.get('password1')

        user = User.objects.create_user(username, email, password)
        user.is_active = False
        user.save()
        return user

    def send_conf_mail(self):
        conf_loc_url = reverse('judge:activate', args=(self.confirm.code,))
        conf_url = settings.SITE_HOST + conf_loc_url

        sender = settings.EMAIL_HOST_USER
        to = self.user.email
        subject = 'JudgeSystem account confirmation'

        plaintext = get_template('judge/confirm_email.txt')
        html      = get_template('judge/confirm_email.html')
        
        context = Context({
            'username': self.user.username, 'conf_url': conf_url})

        text_content = plaintext.render(context)
        html_content = html.render(context)

        msg = EmailMultiAlternatives(subject, text_content, sender, [to])
        msg.attach_alternative(html_content, 'text/html')
        msg.send()

    def post(self, request):
        self.form = RegisterForm(request.POST)
        
        if not self.form.is_valid():
            return self.render(request)

        self.user = self.get_user()
        self.confirm = Confirmation(user = self.user)
        self.confirm.save()

        self.send_conf_mail()

        redir_url = reverse('judge:problem_list')
        return HttpResponseRedirect(redir_url)

class Logout(View):
    def get(self, request):
        logout(request)
        url = reverse('judge:problem_list')
        return HttpResponseRedirect(url)

class Confirm(View):
    def get(self, request, code):
        confList = Confirmation.objects.filter(code = code)

        if not confList.exists():
            error_url = reverse('judge:problem_list')
            return HttpResponseRedirect(error_url)

        conf = confList[0]
        conf.delete()

        user = conf.user
        user.is_active = True
        user.save()

        redir_url = reverse('judge:login')
        return HttpResponseRedirect(redir_url)

judge/views/solution.py
import datetime

from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.urlresolvers import reverse
from django.forms import Form, CharField, Textarea
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponse, HttpResponseRedirect,\
        HttpResponseForbidden
from django.views.generic import DetailView, View
from django.utils import timezone

from judge.models import Solution, Problem, UserProblemData, UserStats
from judge.tasks import test_solution

class MayViewSolutionMixin(UserPassesTestMixin):
    def test_func(self):
        if self.request.user.has_perm('judge.view_foreign_solution'):
            return True
        else:
            pk = self.request.path_info.split('/')[2]
            solution = get_object_or_404(Solution, pk = int(pk))
            return solution.user_id == self.request.user.id

class SolutionDetails(MayViewSolutionMixin,View):
    template_name = 'judge/solution_details.html'

    def get(self, request, pk):
        sol = get_object_or_404(Solution, pk = pk)
        
        context = { 
            'solution': sol,
            'results_by_group': sol.get_results_by_group(),
            'pk': sol.pk,
        }
        return render(request, self.template_name, context)

class SolutionSource(MayViewSolutionMixin, View):
    def get(self, request, pk):
        sol = get_object_or_404(Solution, pk = pk)
        return HttpResponse(sol.source, content_type = 'text/plain')

class SolutionSubmitForm(Form):
    source = CharField(label = 'Source Code',
                            widget = Textarea())

class SolutionSubmit(LoginRequiredMixin, View):
    template_name = 'judge/solution_submit.html'
            
    def render(self, request):
        context = {
            'problem': self.problem,
            'form': self.form,}
        return render(request, self.template_name, context)

    def get(self, request, pk):
        self.form = SolutionSubmitForm()
        if request.user.has_perm('judge.problem_hidden'):
            self.problem = get_object_or_404(Problem, pk = pk)
        else:
            self.problem = get_object_or_404(Problem, pk = pk, visible = True)

        return self.render(request)

    def post(self, request, pk):
        self.problem = get_object_or_404(Problem, pk = pk)
        self.form = SolutionSubmitForm(request.POST)
        
        user = request.user

        if not self.form.is_valid():
            return self.render(request)

        data = UserProblemData.get_for_user_problem(user, self.problem)
        nextSubmit = data.last_submit + datetime.timedelta(seconds = 30)

        if nextSubmit > timezone.now():
            timeLeft = nextSubmit - timezone.now()
            messageText = 'You can submit a solution once every 30 seconds.\
                Try again in {0} seconds'. format(timeLeft.seconds)
            messages.warning(request, messageText)
            return self.render(request)
        else:
            data.last_submit = timezone.now()
            data.save()

        source = self.form.cleaned_data['source']
        solution = Solution(
            source = source,
            submit_date = timezone.now(),
            user = user,
            problem = self.problem)

        solution.save()
        test_solution(solution).delay()

        url = reverse('judge:solution_details', args = (solution.pk,))
        return HttpResponseRedirect(url)

judge/templates/judge/login.html
{% extends 'judge/base.html' %}
{% load bootstrap3 %}

{% block navbar %}
	{% include 'judge/navbar.html' with page='login'%}
{% endblock %}

{% block title %}
	<h1> Login </h1>
{% endblock %}

{% block content %}
	<div class="well well-lg">
		<form method = "POST" action = "{{request.get_full_path}}">
			{% bootstrap_form form %}

			{% buttons %}
				<input type="submit" class="btn btn-primary" value="Log in">
				<a href="{% url 'judge:register' %}" class="btn btn-info">
					Register
				</a>
			{% endbuttons %}
			<a href="{% url 'judge:password_reset' %}">Reset password</a>
			{% csrf_token %}
		</form>
	</div>
{% endblock %}

judge/templates/judge/model_delete.html
{% extends 'judge/problem_edit_base.html' %}

{% block title %}
<h1> 
	Delete 
	<span class="text-primary">
		{{modelName}}
	</span> 
</h1>
{% endblock %}

{% block edit_content %}
	<div class="well well-lg">
		<p class = "lead">
		Are you sure you want to delete this {{ modelType }} ?
			It will be deleted 
			<span class="text-danger">
				FOREVER
			</span>
		</p>
		<div class="row">
			<div class="col-sm-6">
				<form method="POST" action="{{ request.get_full_path}}">
					{% csrf_token %}
					<input type="submit" class="btn btn-default btn-block" 
						  value="Yes, I'm sure">
				</form>
			</div>
			<div class="col-sm-6">
				<a href="{{ cancelUrl }}" class="btn btn-primary btn-block">
					I've changed my mind ...
				</a>
			</div>
		</div>
	</div>
{% endblock %}

{% block edit_nav %}
	{% include 'judge/problem_edit_nav.html' with page='delete' %}
{% endblock %}

judge/templates/judge/password_reset.html
{% extends 'judge/base.html' %}
{% load bootstrap3 %}

{% block navbar %}
	{% include 'judge/navbar.html' %}
{% endblock %}

{% block title %}
	<h1>Password reset</h1>
{% endblock %}

{% block content %}
<div class="well well-lg">
	<form method="POST" action="{{request.get_full_path}}">
		{% bootstrap_form form %}
		{% buttons %}
			<input class="btn btn-primary" type="submit" value="Reset password">
			<a class="btn btn-info" href="{% url 'judge:login' %}">
				Login
			</a>
		{% endbuttons %}
		{% csrf_token %}
	</form>
</div>
{% endblock content %}

judge/templates/judge/problem_delete.html
{% extends 'judge/problem_edit_base.html' %}
{% load judge %}

{% block title %}
<h1> 
    Delete {{ problem.title }}
</h1>
{% endblock %}

{% block breadcrumb_active %}
    Delete problem
{% endblock %}

{% block edit_content %}
		<p class="lead">
		Are you sure you want to delete this {{ modelType }} ?
			It will be deleted 
			<span class="text-danger">
				FOREVER
			</span>
		</p>
		<form method="POST" action="{{ request.get_full_path}}">
			{% csrf_token %}
			<input type="submit" class="btn btn-danger btn-block" 
				  value="Delete problem">
		</form>
{% endblock %}

{% block edit_nav %}
	{% problem_edit_nav page='delete' %}
{% endblock %}

judge/templates/judge/problem_edit.html
{% extends 'judge/problem_edit_base.html' %}
{% load bootstrap3 %}
{% load markdown_deux_tags %}
{% load judge %}

{% block title %}
	<h1> Edit statement </h1>
{% endblock %}

{% block breadcrumb_active %}
    Edit statement
{% endblock %}

{% block edit_content %}
	<form method = "POST" action = "{{request.get_full_path}}">
		{% csrf_token %}
		{% bootstrap_form form %}

		{% buttons %}
			<input type="submit" value="Submit"
				 class="btn btn-primary btn-block"> 
		{% endbuttons %}
	</form>
{% endblock %}

{% block edit_nav %}
	{% problem_edit_nav page='statement' %}
{% endblock %}

judge/templates/judge/problem_import.html
{% extends 'judge/base.html' %}
{% load bootstrap3 %}
{% load judge %}

{% block title %}
<h1> 
	Import problem
</h1>
{% endblock %}

{% block content %}
    <ol class="breadcrumb">
        <li><a href="{% url 'judge:problem_list' %}">Problems</a></li>
        <li class="active">Import</li>
    </ol>
<p class="lead">
	A previously serialized problem can be imported from here.
</p>
<form method="POST" enctype="multipart/form-data" 
	action="{{ request.get_full_path}}">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" class="btn btn-primary btn-block" 
		  value="Import">
</form>
{% endblock %}

judge/templates/judge/problem_list.html
{% extends 'judge/base.html' %}

{% load bootstrap_pagination %}
{% load taggit_templatetags2_tags %}
{% load judge %}

{% block title %}
	<h1>
		Problem list
		{% problem_admin_panel %}
	</h1>
{% endblock %}

{% block content %}
    <ol class="breadcrumb">
        <li class="active">Problems</li>
    </ol>
	<div class="row">
		<div class="col-md-8">
			<ul class="list-group">
			{% for problem in page.object_list %}
				<li class="list-group-item">
					<div class="row">
						<div class="col-sm-4">
							<a href="
								{% url 'judge:problem_details' problem.id %}">
								{{ problem.title }}
							</a>
						</div>
						<div class="col-sm-8">
							{% if not problem.visible %}
							<span class="label label-warning tag-label">
								Hidden
							</span>
							{% endif %}
							{% if problem.status == 'solved' %}
							<span class="label label-success tag-label">
									Solved
								</span>
							{% elif problem.status == 'attempted' %}
								<span class="label label-warning tag-label">
									Attempted
								</span>
							{% endif %}

							{% for tag in problem.tags.names %}
							<a href="{{ curTags|tags_url:tag }}">
								<span class="label tag-label
										{% if tag in curTags %}label-info
										{% else %}label-primary{% endif %}">
									{{tag}}
								</span>
							</a>
							{% endfor %}
						</div>
					</div>
				</li>
			{% endfor %}
			</ul>
		{% bootstrap_paginate page url_extra_kwargs=paginate_extra_kwargs url_view_name=paginate_name range=20 %}
		</div>
		<div class="col-md-4">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">
						Tags
					</h3>
				</div>
				<div class="panel-body">
					{% tag_select %}
					<div class="form-group">
						<button class="btn btn-primary form-control tag-search">
							Search
						</button>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

{% block javascript %}
{{ block.super }}
<script>
	$(document).ready(function() {
		$('.tag-select').select2({
			placeholder: 'choose tags'
		}).val({{ curTags|safe }}).trigger('change');
	});
</script>
{% endblock %}

judge/templates/judge/problem_media.html
{% extends 'judge/problem_edit_base.html' %}
{% load judge %}
{% load media_manager %}

{% block title %}
	<h1>Manage media</h1>
{% endblock %}

{% block breadcrumb_active %}
    Manage media
{% endblock %}

{% block edit_content %}
	<h3>Upload Media</h3>
	{% media_upload problem %}
	<h3>Media for this problem</h3>
	{% media_list problem %}
{% endblock %}

{% block edit_nav %}
	{% problem_edit_nav page='media' %}
{% endblock %}

judge/templates/judge/problem_retest.html
{% extends 'judge/problem_edit_base.html' %}
{% load judge %}

{% block title %}
	<h1>Retest problem</h1>
{% endblock %}

{% block breadcrumb_active %}
    Retest problem
{% endblock %}

{% block edit_content %}
	<p class="lead">
		This is intended to be used only when the test have been modified.
		Pressing the button bellow will test all the solutions on all tests 
		again. Note that there are {{ solutionCount  }} solutions and the 
		retest may take a long time.
	</p>
	<form method="POST" action="{{ request.get_full_path }}">
		{% csrf_token %}
		<input type="Submit" value="Start retest" 
					   class="btn btn-primary btn-block">
	</form>
{% endblock %}

{% block edit_nav %}
	{% problem_edit_nav page='retest' %}
{% endblock %}

judge/templates/judge/register.html
{% extends 'judge/base.html' %}
{% load bootstrap3 %}

{% block navbar %}
	{% include 'judge/navbar.html' with page='register' %}
{% endblock %}

{% block title %}
	<h1>Register</h1> 
{% endblock %}

{% block content %}
	<div class="well well-lg">
		<form method="POST" action="{% url 'judge:register' %}">
			{% csrf_token %}
			{% bootstrap_form form %}

			{% buttons %}
				<input type="submit" class="btn btn-primary" value="Register">
				<a href="{% url 'judge:login' %}" class="btn btn-info">
					Log in
				</a>
			{% endbuttons %}

		</form>
	</div>
{% endblock %}

judge/templates/judge/solution_submit.html
{% extends 'judge/base.html'  %}

{% load bootstrap3 %}
{% load base %}

{% block title %}
	<h1> 
		Submit {{ problem.title }} 
		{% if not problem.visible %}
			<small>Hidden</small>
		{% endif %}
	</h1>
{% endblock %}

{% block content %}
<form method = "POST" action = "{% url 'judge:solution_submit' problem.id %}">
	{% csrf_token %}
	{% bootstrap_form form %}

	<input type="submit" value="Sumit solution" 
		class="btn btn-primary btn-block">
</form>

{% endblock content %}

judge/templates/judge/tag_select.html
{% load taggit_templatetags2_tags %}

{% get_taglist as tags for 'judge.problem' %}
<div class="form-group">
	<label class="control-label" for="tag-select">
		Select tags
	</label>
	<select class="form-control tag-select" multiple
		id="tag-select" name="tags">
		{% for tag in tags %}
			<option value="{{ tag }}">{{ tag }}</option>
		{% endfor %}
	</select>
</div>

judge/templates/judge/test_group_list.html
{% extends 'judge/problem_edit_base.html' %}
{% load bootstrap3 %}
{% load judge %}

{% block title %}
	<h1>Test groups</h1>
{% endblock %}

{% block edit_content %}
{% if test_groups %}
	<table class="table">
		<thead>
			<tr>
				<th>Name</th>
				<th>Points</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
		</thead>
		<tbody>
			{% for group in test_groups %}
			<tr>
				<td>{{ group.name }}</td>
				<td>{{ group.score }}</td>
				<td>
					<a href="{% url 'judge:test_group_edit' group.pk %}"
						class="btn btn-primary btn-xs btn-block">
						Edit
					</a>
				</td>
				<td>
					<a href="{% url 'judge:test_group_delete' group.pk %}"
						class="btn btn-warning btn-xs btn-block">
						Delete
					</a>
			</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>No test groups are found</p>	
{% endif %}
<a href="{% url 'judge:test_group_new' problem_pk %}"
   class="btn btn-block btn-primary">
	New Test group
</a>
{% endblock %}

{% block edit_nav %}
	{% problem_edit_nav page='test_groups' %}
{% endblock %}

judge/templates/judge/test_select.html
{% if tests %}
<table class="table table-hover">
	<thead>
		<tr>
			<th>
				<input type="checkbox" class="select-all" 
						   selection=".{{ select_class }}">
				Select all
			</th>
			<th>Time limit</th>
			<th>Memory limit</th>
			<th>Points</th>
			<th>Input</th>
			<th>Output</th>
			<th>Edit</th>
			<th class="text-warning">Delete</th>
		</tr>
	</thead>
	<tbody>
		{% for test in tests %}
			<tr>
				<td>
					<input type="checkbox" name="test-select"
						class="{{ select_class }}" value="{{ test.pk }}"
						{% if test in selected %} checked {% endif %}>
					{{ test.pk }}
				</td>
				<td> {{ test.time_limit|floatformat }} sec </td>
				<td> {{ test.mem_limit }} MB </td>
				<td> 
					{% if test.test_group_id %}
						-
					{% else %}
						{{ test.score|floatformat }} 
					{% endif %}
				</td>
				<td>
					<a href="{% url 'judge:test_input' test.pk %}">
						Input
					</a>
				</td>
				<td>
					<a href="{% url 'judge:test_output' test.pk %}">
						Output
					</a>
				</td>
				<td>
					<a href="{% url 'judge:test_edit' test.pk %}"
						class="btn btn-primary btn-xs btn-block">
						Edit
					</a>
				</td>

				<td>
					<a href="{% url 'judge:test_delete' test.pk %}" 
						class="btn btn-warning btn-xs btn-block">
						Delete
					</a>
				</td>
			</tr>
		{% endfor %}
	</tbody>
</table>
{% else %}
<p>No tests</p>
{% endif %}